/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as WorkersWorkerIdRouteImport } from './routes/workers.$workerId'
import { Route as ProjectsCompanyIdRouteImport } from './routes/projects.$companyId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ProjectsCompanyIdIndexRouteImport } from './routes/projects.$companyId.index'
import { Route as ProjectsCompanyIdSectionRouteImport } from './routes/projects.$companyId.$section'
import { Route as ProjectsCompanyIdCpaMonthIdRouteImport } from './routes/projects.$companyId.cpa.$monthId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const WorkersWorkerIdRoute = WorkersWorkerIdRouteImport.update({
  id: '/workers/$workerId',
  path: '/workers/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCompanyIdRoute = ProjectsCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ProjectsCompanyIdIndexRoute = ProjectsCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsCompanyIdRoute,
} as any)
const ProjectsCompanyIdSectionRoute =
  ProjectsCompanyIdSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => ProjectsCompanyIdRoute,
  } as any)
const ProjectsCompanyIdCpaMonthIdRoute =
  ProjectsCompanyIdCpaMonthIdRouteImport.update({
    id: '/cpa/$monthId',
    path: '/cpa/$monthId',
    getParentRoute: () => ProjectsCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/projects/$companyId': typeof ProjectsCompanyIdRouteWithChildren
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/projects/$companyId/$section': typeof ProjectsCompanyIdSectionRoute
  '/projects/$companyId/': typeof ProjectsCompanyIdIndexRoute
  '/projects/$companyId/cpa/$monthId': typeof ProjectsCompanyIdCpaMonthIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/projects/$companyId/$section': typeof ProjectsCompanyIdSectionRoute
  '/projects/$companyId': typeof ProjectsCompanyIdIndexRoute
  '/projects/$companyId/cpa/$monthId': typeof ProjectsCompanyIdCpaMonthIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/projects/$companyId': typeof ProjectsCompanyIdRouteWithChildren
  '/workers/$workerId': typeof WorkersWorkerIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/projects/$companyId/$section': typeof ProjectsCompanyIdSectionRoute
  '/projects/$companyId/': typeof ProjectsCompanyIdIndexRoute
  '/projects/$companyId/cpa/$monthId': typeof ProjectsCompanyIdCpaMonthIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/login'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/clients/$clientId'
    | '/projects/$companyId'
    | '/workers/$workerId'
    | '/projects/'
    | '/workers/'
    | '/projects/$companyId/$section'
    | '/projects/$companyId/'
    | '/projects/$companyId/cpa/$monthId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/login'
    | '/payments'
    | '/reports'
    | '/clients/$clientId'
    | '/workers/$workerId'
    | '/projects'
    | '/workers'
    | '/projects/$companyId/$section'
    | '/projects/$companyId'
    | '/projects/$companyId/cpa/$monthId'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/login'
    | '/payments'
    | '/projects'
    | '/reports'
    | '/clients/$clientId'
    | '/projects/$companyId'
    | '/workers/$workerId'
    | '/projects/'
    | '/workers/'
    | '/projects/$companyId/$section'
    | '/projects/$companyId/'
    | '/projects/$companyId/cpa/$monthId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  WorkersWorkerIdRoute: typeof WorkersWorkerIdRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/workers/$workerId': {
      id: '/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof WorkersWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$companyId': {
      id: '/projects/$companyId'
      path: '/$companyId'
      fullPath: '/projects/$companyId'
      preLoaderRoute: typeof ProjectsCompanyIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/projects/$companyId/': {
      id: '/projects/$companyId/'
      path: '/'
      fullPath: '/projects/$companyId/'
      preLoaderRoute: typeof ProjectsCompanyIdIndexRouteImport
      parentRoute: typeof ProjectsCompanyIdRoute
    }
    '/projects/$companyId/$section': {
      id: '/projects/$companyId/$section'
      path: '/$section'
      fullPath: '/projects/$companyId/$section'
      preLoaderRoute: typeof ProjectsCompanyIdSectionRouteImport
      parentRoute: typeof ProjectsCompanyIdRoute
    }
    '/projects/$companyId/cpa/$monthId': {
      id: '/projects/$companyId/cpa/$monthId'
      path: '/cpa/$monthId'
      fullPath: '/projects/$companyId/cpa/$monthId'
      preLoaderRoute: typeof ProjectsCompanyIdCpaMonthIdRouteImport
      parentRoute: typeof ProjectsCompanyIdRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ProjectsCompanyIdRouteChildren {
  ProjectsCompanyIdSectionRoute: typeof ProjectsCompanyIdSectionRoute
  ProjectsCompanyIdIndexRoute: typeof ProjectsCompanyIdIndexRoute
  ProjectsCompanyIdCpaMonthIdRoute: typeof ProjectsCompanyIdCpaMonthIdRoute
}

const ProjectsCompanyIdRouteChildren: ProjectsCompanyIdRouteChildren = {
  ProjectsCompanyIdSectionRoute: ProjectsCompanyIdSectionRoute,
  ProjectsCompanyIdIndexRoute: ProjectsCompanyIdIndexRoute,
  ProjectsCompanyIdCpaMonthIdRoute: ProjectsCompanyIdCpaMonthIdRoute,
}

const ProjectsCompanyIdRouteWithChildren =
  ProjectsCompanyIdRoute._addFileChildren(ProjectsCompanyIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsCompanyIdRoute: typeof ProjectsCompanyIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsCompanyIdRoute: ProjectsCompanyIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  WorkersWorkerIdRoute: WorkersWorkerIdRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
